//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Orchestrion")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) Navaneeth, 2013")]
[assembly: System.Reflection.AssemblyVersion("0.1.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.1.0.20130604")]


